const CONFIG = {
    titleWeb: "To my Tiramisu",
    introTitle: 'Chang miu aka Tracy',
    introDesc: `hôm nay chắc em mệt mỏi và downmood nhiều lắm nhưng hãy cố gắng ăn uống đầy đủ, uống chút nước ấm và nghỉ ngơi thật nhiều nhéeee`,
    btnIntro: 'Sending you all my love',
    title: 'Cái này có lẽ không cool ngầu như trái tim em gửi anh nhưng mong em không thấy nó quá ngớ ngẩn 🥰',
    desc: 'Hôm nay hãy nghỉ ngơi và cuộn tròn như 1 bé mèo nhé :> ',
    btnYes: 'Vâng ạ!!!',
    btnNo: 'Không nha :3',
    question: 'Trên thế giới hơn 7 tỉ người mà sao người đáng yêu như em bây giờ anh mới tìm thấy vậyyyy <3',
    btnReply: 'Gửi cho em <3',
    reply: ' <33333333',
    mess: 'Em từng khiến cho 1 ngày tồi tệ của anh bỗng dưng trở nên vui vẻ và hạnh phúc hơn nên anh mong chút ngớ ngẩn này sẽ khiến em upmood lên 1 chút 🥰 😘😘',
    messDesc: 'Nhắn tin cho anh khi em thấy đỡ hơn nha',
    btnAccept: 'Okiiiii lun <3',
    
